# render.yaml
services:
  - type: web # Keep as web for the free tier
    name: binary-trading-bot # Corrected typo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py # Changed to run the Flask wrapper
    # envVars: section removed - Set TELEGRAM_BOT_TOKEN in Render Dashboard Environment
