# render.yaml
services:
  - type: worker
    name: binary-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python watchdog.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7677936243:AAEfZ-LzsWC-gEnE5TKiM7WCGnQilTL1MyU
      - key: ADMIN_CHAT_ID
        value: 5679669495
      - key: SIGNAL_TIMEFRAMES
        value: 1,5
    plan: free
